### PR TITLE
adding react 0.14 support

### LINKED ISSUE #52: react 0.14 support
It's breaking right now:

image

### PR DESCRIPTION
**Pull request by luisrudge**
this fixes #52

There's only one issue that I need your help.

`var LinkedValueUtils = require('react/lib/LinkedValueUtils');`

This doesn't exist in react 0.14 and ReactLink [will be deprecated](https://github.com/facebook/react/issues/2302) in the future.

So.. what should we do?

### CODE REVIEW

**Comment by frontendphil** [comment]
Hmm... That's not really React 0.14 support, but a strict dependency on it. I'm fine using 0.14 in the for our gh-pages. But I would say that `*.getDOMNode()` should be replace by `React.findDOMNode(...)` for now. This would make it possible to run react-mentions both on 0.13.x and 0.14. Regarding `LinkedValueUtils` I would need to talk to @jfschwarz. My best guess would be to simply add our own version, since this thing is really not that hard to implement.

**Comment by frontendphil** [comment]
@jfschwarz should also be around next week. He might also be ok with strictly doing a 0.14 version and bumping the major.

**Comment by luisrudge** [comment]
Yeah.. the name is a bit misleading.. But we have to move forward anyway.. There's no reason to continue supporting 0.13, IMO. We should just bump the version as this is a breaking change and move on.

About `findDOMNode`:
From React docs:

> If you need access to the underlying DOM node for that component, you can use ReactDOM.findDOMNode as an "escape hatch" but we don't recommend it since it breaks encapsulation and in almost every case there's a clearer way to structure your code within the React model.

Also, `findDOMNode` doesn't work with 0.14 stateless components.

**Comment by luisrudge** [comment]
#54 is better

**Pull request closed without merging**
