### PR TITLE
Add vertical scrolls

### PR DESCRIPTION
**Pull request by trickeyone**

### CODE REVIEW

**Comment by frontendphil** [comment]
Hey there, thanks for the PR but help me understand what problem you are trying to solve? 

Also, you're using a deprecated and since then already removed API `getDOMNode` and have not added any tests for your code.

**Comment by trickeyone** [comment]
Hi frontendphil.

The problem was that I needed to be able to control scrolling in the mentions element. The current behavior is to simply continuously increase the height of the mentions DIV, which was a very undesirable behavior.

The main changes were small: a single CSS change to make the MentionInput DIV element relative position instead of absolute; and made the MentionInput DIV element's top position equal that of the textarea's scrollTop.

The reason for the, now, out-dated getDomNode was because the actual code change was from last year, I just never made a PR. And, since this was a UI-ish change, I didn't add a test. I've had problems in the past with doing UI tests for React.

**Comment by frontendphil** [comment]
Alright, could you please first base your changes on the latest version of our code base? Looking at your code, I can see that this is not the case. 

Furthermore you are accessing a `ref` (input) inside a render method, which is discouraged. Please put this code inside a lifecycle hook.

**Comment by jfschwarz** [comment]
Closing this for inactivity. 

(Also, it should already be possible to add vertical scrolling in user land by wrapping the mentions input in a div with fixed height and `overflow: auto`. Syncing scroll positions does not seem to be the best solution.)

**Comment by jgrisafe** [comment]
@jfschwarz I'm not sure this fixes the problem as the mentions list popover will be hidden inside the scroll. If we want vertical scroll but allow the metions list to bleed out of the scroll, we will need a different solution.

**Pull request closed without merging**
