### PR TITLE
docs: react-instantsearch example

### LINKED ISSUE #190: Add an async example with Algolia
I'd like to make an example of how to use this with [React InstantSearch](https://github.com/algolia/react-instantsearch), and was wondering if an example similar to [ant-mentions](https://github.com/algolia/react-instantsearch/tree/master/packages/react-instantsearch/examples/autocomplete) could be useful here 😄

### PR DESCRIPTION
**Pull request by Haroenv**
fixes #190

I have some questions I left as comments because I don't totally understand the architecture of this library, it would be nice if someone could clarify that for me. Thanks!

Because of those comments it doesn't work completely yet, it would be nice to figure out!

@frontendphil 😄

### CODE REVIEW

**Comment by Haroenv** [comment]
Is it also possible to use a Promise instead of a callback in `data`? That's a significant amount simpler to read IMO

**Comment by jfschwarz** [comment]
Yes, you can also return a promise in the function you pass to `data`.

**Comment by Haroenv** [comment]
I'd rather use the connectAutocomplete, and be in full control over what to render, rather than leave it opaque to this library, especially concerning highlighting, which is something which can easily leave XSS holes, which is why we solved it in the frontend libraries and not in the API client. 

Do you see a way in which it would be possible to configure the highlighting myself (give an array with objects which are highlighted: true/ false and content)?  

This solution would also align the library to be used for a part of an interface which already works with InstantSearch for the facets for example

**Comment by jfschwarz** [comment]
> Do you see a way in which it would be possible to configure the highlighting myself (give an array with objects which are highlighted: true/ false and content)?

Absolutely. Check out the `renderSuggestion` prop of the `Mention` component here: https://github.com/effektif/react-mentions#configuration

**Comment by Haroenv** [comment]
The work you're doing in `MentionsInput` and `Mentions` seems to work against the work we're doing in React InstantSearch, so I'll leave using the API client as an exercise to the reader since it's trivial, but using React InstantSearch seems to be mostly impossible.

**Pull request closed without merging**
