### PR TITLE
Fix some loose ends

### PR DESCRIPTION
**Pull request by glifchits**
Hey there, we're quite enjoying using this library. I patched up a couple of things for our own sake, but hopefully they're helpful fixes. I fixed these two things:

First, the `onAdd` callback which is provided in the example ([see here](https://github.com/effektif/react-mentions/blob/5584cd70804d8a5acd3ad1925b92b07d559c60bc/gh-pages/views/examples/MultipleTriggerView.jsx#L43)) is potentially very useful, but was never actually called in the component source.

Secondly, I was getting an issue thanks to `displayTransform` being invoked [here](https://github.com/effektif/react-mentions/commit/bd16d946096f505c745edd2184ed5df7b3744dd3#diff-33f942b6199400cd55d6c8dd0f4a843cR499) when it was still the default value `null`.

Let me know if this is suitable to be pulled in. Thanks!

### CODE REVIEW

**Comment by glifchits** [comment]
While we're at it, the bug that I addressed in 083fd11 is not visible on the gh-pages example because the code was not compiled. An update of the example site would be nice :)

**Comment by frontendphil** [comment]
Hey could you integrate the latest master into the pull request?

**Comment by frontendphil** [comment]
Thanks! @jfschwarz is going to look into the pull request asap.

**Comment by jfschwarz** [comment]
Thanks, this looks really good! :+1:

**Comment by jfschwarz** [comment]
I will just update the signature of the onAdd method to `function (id, display)` as this is more consistent to the displayTransform prop.

**Pull request merged**
