### PR TITLE
upgraded to substyle v5

### PR DESCRIPTION
**Pull request by jfschwarz**
Breaking change: If the component should be used with Radium, the user has to wrap it in substyle's `EnhancerProvider`. react-mentions will no longer automatically pickup Radium if it is installed.

### CODE REVIEW

**Comment by frontendphil** [comment]
Wouldn't that mean SemVer: Major? :)

**Comment by jfschwarz** [comment]
we are still on `v0.x` version line

**Comment by frontendphil** [comment]
Oh how I hate that... Don't you think react-mentions deserves a 1.0?

**Comment by jfschwarz** [comment]
I had just one other thought: Should we rather re-export substyle's `EnhancerProvider`? This would save users for adding substyle as a dependency even if they want to use Radium.

**Comment by frontendphil** [comment]
We could do that... Even though it sounds hacky...

**Pull request merged**
