### PR TITLE
set selectionStartBeforeChange & selectionEndBeforeChange if necessary

### PR DESCRIPTION
**Pull request by evankline**
If the input is focused programmatically the values for ```selectionStartBeforeChange``` and ```selectionEndBeforeChange``` will be null. This causes the ```handleChange``` function in MentionInputs.js to set the event target's value that is passed to the onChange handler with the current value of the input appended to the correct value. For example, a user enters "fo" & then blurs the input. On keypress, of the letter "o" the input is focused and the input holds the value "foofo" instead of the value "foo".

### CODE REVIEW

**Comment by eudisd** [comment]
+1

**Comment by jfschwarz** [comment]
I don't quite get how to reproduce this problem. Could you elaborate a bit?

**Comment by evankline** [comment]
@jfschwarz please see this [gist](https://gist.github.com/evankline/538f2fedae996ab1f93b)

**Comment by jfschwarz** [comment]
Alright, thanks for the PR! There was still a problem when setting the focus in `onpaste`, so I pushed a slightly modified version of your fix with https://github.com/effektif/react-mentions/commit/0725dce201af24bef1be5667d023ecaa214c8f22.

**Comment by evankline** [comment]
Awesome, thanks @jfschwarz!

**Pull request closed without merging**
